services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
